# Generated by Django 4.1.1 on 2022-10-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_favouritepost_postfavourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postfavourite',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='user',
            new_name='author',
        ),
    ]
