# Generated by Django 4.1.1 on 2022-10-01 15:21

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('firstName', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=25, verbose_name='Last Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='usersPictures/', verbose_name='Picture')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff Member')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
